Project2/ImageMajik/config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'login#new'
  get 'logout' => 'login#destroy'
  get 'register' => 'users#new'

  get 'image/info/:id/:vid' => 'image#get_image_info'
  get 'image/view'
  post 'image/share'
  post 'image/upload'
  post 'image/edit'
  post 'image_version.:id' => 'image#restore'
  delete 'image_version.:id' => 'image#delete'

  get 'users/info'

  root 'general#index'

  resources :users
  resources :login
  resource :image_version
end

Project2/ImageMajik/app/views/shared/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <a class="navbar-brand">Image Majik</a>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-left">
            <li>
                <%= link_to 'Home', root_path %>
            </li>
            <% if current_user %>
            <li>
                <a href="#" data-toggle="modal" data-target="#upload_modal">
                    Upload
                </a>
            </li>
            <li>
                <%= link_to 'MyImages', controller: 'image', action: 'view' %>
            </li>
            <% end %>
        </ul>

        <% if current_user %>
        <p class="navbar-text navbar-right">
            Logged in as <%= link_to current_user.name, current_user %> (<%= link_to "Logout", logout_path %>)
        </p>
        <% else %>
        <ul class="nav navbar-nav navbar-right">
            <li>
                <%= link_to "Log In", login_path %>
            </li>
            <li>
                <%= link_to "Register", register_path %>
            </li>
        </ul>
        <% end %>
    </div>
</nav> <!-- end nav -->

Project2/ImageMajik/app/views/shared/_upload_modal.html.erb
<div class="modal fade" id="upload_modal" tabindex="1" role="dialog" 
  aria-labelledby="#upload_modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="upload_modal_title">
                    Upload Image
                </h4>
            </div>

            <div class="modal-body">
            <%= form_tag({controller: "image", action: "upload"},
              multipart: true) do %>
                <div class="form-group">
                    <%= label_tag 'Select image' %> <br>
                    <%= file_field_tag 'image', 
                      accept: IMAGE_MIME_TYPES.join(',')
                    %>
                </div>
                <button type="submit" class="btn btn-primary">Upload</button>
            <% end %>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>